Дипломный проект
TodayIsMay/java-explore-with-me pull request #2
Opened 2022-10-04 20:37 UTC by TodayIsMay

2022-10-05 19:58 UTC, sergeymamonov requested changes

2022-10-05 19:58 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/explorewhithme/exception/ErrorHandler.java
> +    }
А если еще какая-то ошибка выскачет в рантайме кроме этих двух? Лучше сделать, чтобы обработчик на INTERNAL_SERVER_ERROR ловил все необрабатываемые исключение.

2022-10-05 19:58 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/explorewhithme/mapper/CategoryMapper.java
> +        Category category = new Category();
На вход в этот метод может придти null? Если да, то в следующей строке будет NPE.

2022-10-05 19:58 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/explorewhithme/mapper/CategoryMapper.java
> +        List<CategoryDto> listDto = new ArrayList<CategoryDto>();
Аналогично, может придти null? А в остальные мапперы может придти null?

2022-10-05 19:58 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/explorewhithme/mapper/CompilationMapper.java
> +        CompilationDto compilationDto = new CompilationDto(eventsDto, compilation.getId(), compilation.getPinned(),
Можно сразу возвращать из метода созданный объект, а не записывать его в лишнюю переменную.

2022-10-05 19:58 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/explorewhithme/repository/EventRepository.java
> +    @Query(" select e from Event e " +
В файле CompilationRepository операторы SQL написаны заглавными буквами, здесь строчными. Лучше чтобы было единообразие во всех файлах.

2022-10-05 19:58 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/explorewhithme/service/CompilationService.java
> +        } else throw new RuntimeException("Compilation id= " + id + " not found");
В других классах логи писались на русском языке, здесь и далее -  на английском. Лучше чтобы было единообразие. 

Здесь действительно необходимо кидать RuntimeException? Никакая из созданных ошибок не подходит? Может лучше создать тогда, если нет?

2022-10-05 19:58 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/explorewhithme/service/RequestService.java
> +            throw new RuntimeException();
В логе будет RuntimeException. Из такого лога не очень понятно будет причина ошибки. Логи нужно писать информативное, чтобы сообщение помогало понять причину произошедшего. Ниже аналогично, кидание ошибок RuntimeException - не информативно.

2022-10-05 19:58 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/explorewhithme/service/RequestService.java
> +        if (event.getParticipantLimit() != 0) {
Два ифа подряд, их условия можно соединить через &&.

2022-10-05 19:58 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/explorewhithme/service/RequestService.java
> +    public Request rejectUserRequests(Long userId, Long eventId, Long requestId) {
Все ли передаваемые в метод параметры используются?

2022-10-05 19:58 UTC, sergeymamonov commented on stats/src/main/java/ru/practicum/explorewhithme/mapper/UriHitsMapper.java
> +        ViewStatsDto viewStatsDto = new ViewStatsDto(uriHits.getApp(), uriHits.getUri(), Long.valueOf(uriHits.getHits()));
Можно сразу возвращать объект без использования промежуточной переменной.

2022-10-05 19:58 UTC, sergeymamonov commented on stats/src/main/java/ru/practicum/explorewhithme/model/EndpointHit.java
> +    String app;
Предложил бы добавить модификатор private для полей класса.

2022-10-06 11:43 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/exception/ErrorHandler.java
> +    }
Done

2022-10-06 11:43 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/mapper/CategoryMapper.java
> +        Category category = new Category();
Отсечётся на уровне контроллера и не придёт.

2022-10-06 11:43 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/mapper/CategoryMapper.java
> +        List<CategoryDto> listDto = new ArrayList<CategoryDto>();
Отсечётся на уровне контроллера и не придёт.

2022-10-06 11:43 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/repository/EventRepository.java
> +    @Query(" select e from Event e " +
Done

2022-10-06 11:43 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/service/CompilationService.java
> +        } else throw new RuntimeException("Compilation id= " + id + " not found");
Done

2022-10-06 11:43 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/service/RequestService.java
> +            throw new RuntimeException();
Done

2022-10-06 11:45 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/service/RequestService.java
> +        if (event.getParticipantLimit() != 0) {
Если соединять, придётся писать длинную причин ошибки типа "Ну у вас проблема либо в том, либо в том, либо в том, угадайте". Я б на каждую проблему написала отдельный if или вообще валидатор где-нибудь в utils, но, честно, сейчас нет ни сил ни времени)
Релиз на работе релизнем и приду шлифовать этот проект.

2022-10-06 11:46 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/service/RequestService.java
> +    public Request rejectUserRequests(Long userId, Long eventId, Long requestId) {
Fixed

2022-10-06 11:46 UTC, TodayIsMay commented on stats/src/main/java/ru/practicum/explorewhithme/model/EndpointHit.java
> +    String app;
Done

2022-10-07 10:04 UTC, sergeymamonov requested changes
1. Не устранено замечание по корректировке pom файлов. (В родительском pom не должно быть блока <dependency>, так как проект многомодульный, и такой блок в родительском pom’е жёстко задаст список зависимостей для всех дочерних модулей, а в нашем случае (и в большинстве случаев) это не нужно. В родительском pom не должно быть блока <build><plugins>…</plugins></build> по тем же причинам, что и блок <dependency>.) 

2. Удалите неиспользуемый импорт, сейчас из-за него не проходит проверка кода.

2022-10-13 08:41 UTC, merged