Comments
TodayIsMay/java-explore-with-me pull request #3
Opened 2022-10-05 11:11 UTC by TodayIsMay

2022-10-05 14:34 UTC, BLRrubik commented
Серьезных замечаний не найдено. Работа выполнена хорошо

2022-10-05 20:12 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +@RequestMapping
[nit] `@RequestMapping("/comments")`

2022-10-05 20:14 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    public CommentDto createComment(@Valid @RequestBody CommentDto commentDto) {
DTO-хи на разные методы эндпоинтов лучше разделять сразу во избежание излишней поддержки.

в текущем сетапе поле для POST также прорастет и в PATCH, чего вероятно не хотелось бы

2022-10-05 20:15 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +        log.info("Новый комментарий: " + savedComment);
лучше debug, чтобы в случае чего отключить и не засорять логи

2022-10-05 20:16 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    @PostMapping("/comments")// Добавить комментарий на своё событие нельзя
[nit] комментарии лучше оформлять в виде javadoc

2022-10-05 20:17 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    public CommentDto createComment(@Valid @RequestBody CommentDto commentDto) {
UPD: у тебя уже пророс id-шник на метод POST

2022-10-05 20:17 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    public CommentDto updateComment(@Valid @RequestBody CommentDto commentDto, @PathVariable long userId) {
а чего не /comments/{commentId}? было бы оч даже по спецификации REST-а

2022-10-05 20:19 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    @GetMapping("/comments/author/{authId}") //Получить все комментарии автора отсортированные по дате создания
эту штуку лучше оформить в виде GET: /comments
тогда authorId станет всего лишь параметром фильтрации (RequestParam). такой эндпоинт гораздо сильнее расширяем, чем существующий.

2022-10-05 20:19 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    public List<CommentDto> getCommentForUser(@PathVariable long authId) {
что будет, если все комментарии пользователя не поместятся в оперативную память?

2022-10-05 20:20 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    public List<CommentDto> getCommentForEvent(@PathVariable long eventId) {
уедет в GET: /comments

2022-10-05 20:20 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    public List<CommentDto> getCommentForEvent(@PathVariable long eventId) {
https://github.com/TodayIsMay/java-explore-with-me/pull/3/files#r988318382

2022-10-05 20:22 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/exception/CommentNotFoundException.java
> +        super(message);
формировать сообщение лучше в конструкторе, передавая айдишник в качестве аргумента конструктора.

в качестве огромного плюса ты избегаешь дублирования и, в случае изменения сообщения, будешь изменять его единожды

2022-10-05 20:23 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/service/CommentService.java
> +        Event event = eventService.findById(comment.getEventId());
тут не проверяется корректность автора. может имеет смысл чекнуть, что такой автор существует

2022-10-05 20:23 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/service/CommentService.java
> +        if (comment.getText() != null) {
а если null, имеет ли смысл это действие?

2022-10-05 20:24 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/service/CommentService.java
> +    public Comment findById(Long id) {
[nit] findByIdOrThrow

2022-10-05 20:24 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/service/CommentService.java
> +        } else throw new CommentNotFoundException("Comment id= " + id + " not found");
[nit]
```
return commentRepository.findById(id)
    .orElseThrow(() -> ...);
```

2022-10-05 20:25 UTC, vbutrim commented on server/src/main/java/ru/practicum/explorewhithme/service/CommentService.java
> +        List<Comment> comments = commentRepository.findByAuthorId(authId);
сортировку лучше вынести на уровень БД

_применимо и для getCommentForEvent_

2022-10-05 20:25 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/service/CommentService.java
> +    public Comment findById(Long id) {
Где примитив? `Long` же. Не `long`.

2022-10-05 20:26 UTC, vbutrim requested changes
гуд стафф
оставил несколько улучшалок

2022-10-05 20:26 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/service/CommentService.java
> +        List<Comment> comments = commentRepository.findByAuthorId(authId);
Ваня, астанавис, и так два дня осталось всего)))

2022-10-06 15:13 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +        log.info("Новый комментарий: " + savedComment);
Done

2022-10-06 15:13 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    @GetMapping("/comments/author/{authId}") //Получить все комментарии автора отсортированные по дате создания
Done

2022-10-06 15:14 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    public List<CommentDto> getCommentForEvent(@PathVariable long eventId) {
Done

2022-10-06 15:14 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/exception/CommentNotFoundException.java
> +        super(message);
Клёвая идея, спасибо, чот мне в голову не приходило. Done.

2022-10-06 15:14 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/service/CommentService.java
> +        if (comment.getText() != null) {
Изменила

2022-10-06 15:15 UTC, TodayIsMay commented on server/src/main/java/ru/practicum/explorewhithme/controller/CommentController.java
> +    public CommentDto updateComment(@Valid @RequestBody CommentDto commentDto, @PathVariable long userId) {
Да, знаю, пусть так полежит, пощади.

2022-10-07 07:53 UTC, vbutrim approved these changes
lgtm

2022-10-13 08:41 UTC, merged